Gender.create!(gender: "Transgender Woman")
Gender.create!(gender: "Transgender Man")
Gender.create!(gender: "Cis Woman")
Gender.create!(gender: "Cis Man")
Gender.create!(gender: "Non-binary / Genderfluid / Genderqueer")
Gender.create!(gender: "None of these apply to me")

KinkInterest.create!(kink_interest: "Prefer not to be matched with someone kinky.")
KinkInterest.create!(kink_interest: "No preference")
KinkInterest.create!(kink_interest: "Prefer to be matched with someone kinky.")

KinkRole.create!(kink_role: "Top")
KinkRole.create!(kink_role: "Bottom")
KinkRole.create!(kink_role: "Switch")
KinkRole.create!(kink_role: "Unsure")
